Settings:
  # 해당 플러그인의 업데이트 체크 여부
  update-check: true
  # 해당 플러그인의 업데이트 체크 주기 (초단위)
  update-check-interval: 3600
  # https://bstats.org/ 해당 사이트에 플러그인 사용 통계를 전송합니다.
  # 해당 기능을 사용하신다면 플러그인 개발자를 구독한거나 다름없습니다!
  # 해당 사이트에서 지원하는 통계의 기능으로 저는 얼마나 많은 서버에서 해당 플러그인을 사용하는지 알 수 있습니다. XD
  use-metrics: true

  # 업데이트 확인에서 제외할 플러그인 목록입니다. (DP-Plugins의 플러그인만 등록시켜주세요.)
  update-check-excluded: [ ]

  use-metrics-excluded: [ ]

  # ex)
#  update-check-excluded:
#    - DP-VirtualStorage

#  use-metrics-excluded:
#    - DP-VirtualStorage

  default-lang: ko_KR

  use-twitch-api: false
  twitch-api-key: ""
  twitch-api-secret: ""
  # 키, 시크릿 생성 : https://dev.twitch.tv/console/extensions/create
  twitch-chatbot-clientID: ""
  twitch-chatbot-accessToken: ""
  # 아이디, 토큰 생성 : https://twitchtokengenerator.com/

